#
# github-comment の設定ファイル
#
# https://suzuki-shunsuke.github.io/github-comment/config/
#
---
exec:
  default:
    template: |
      default-ok
  hello:
    - when: true
      template: |
          exit code: {{.ExitCode}}

          ```
          $ {{.Command}}
          ```

          Stdout:

          ```
          {{.Stdout}}
          ```

          Stderr:

          ```
          {{.Stderr}}
          ```

          CombinedOutput:

          ```
          {{.CombinedOutput}}
          ```
