---
exec:
  default:
    #
    # whenで分岐させない (分岐させる例: ExitCode != 0)
    #
    - when: true
      template: |
        {{template "status" .}} {{template "link" .}}

        exit code: {{.ExitCode}}

        実行されたコマンド

        ```
        $ {{.Command}}
        ```

        <details>

        Output

        ```
        {{.CombinedOutput | AvoidHTMLEscape}}
        ```

        StdErrOut

        ```
        {{.Stderr | AvoidHTMLEscape}}
        ```

        </details>
