---
exec:
  default:
    - when: true
      template: default-ok
  hello:
    - when: true
      template: |
          exit code: {{.ExitCode}}

          実行したコマンド
          ```
          $ {{.Command}}
          ```

         出力
          ```
          {{.CombinedOutput}}
          ```

          標準エラー出力 only
          ```
          {{.Stderr}}
          ```
