#!/bin/bash

################################################################################
# Check for submodule updates
################################################################################
#
# 概要
# - submodule に更新があるかチェック
#
# exit code: 0 : 更新はない ( 最新状態である )
# exit code: 1 : 更新がある
#

GIT_SUBMODULE="akiyadego-openapi"
readonly GIT_SUBMODULE

function exist_diff_from_the_latest() {
  git submodule update --init --recursive --remote "${GIT_SUBMODULE}"
  git status --short ${GIT_SUBMODULE} | wc -l | grep -q 0
}

if exist_diff_from_the_latest; then
  echo "👍 Nothing submodule updates: ${GIT_SUBMODULE} submodule is latest."
  exit 0
else
  echo "🧐 Found submodule updates: ${GIT_SUBMODULE} submodule is up to date." >&2
  exit 1
fi
