---
exec:
  default:
    - when: true
      template: default-ok
  hello:
    - when: true
      complement:
        vars:
          buildlink:
            - type: envsubst
              value: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
              #value: "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
      template: |
        🙅 {{.Vars.buildlink}}

        exit code: {{.ExitCode}}

        実行されたコマンド

        ```
        $ {{.Command}}
        ```

        Output

        ```
        {{.CombinedOutput}}
        ```

        StdErrOut

        ```
        {{.Stderr}}
        ```
