---
vars:
  buildlink:
    - type: template
      value: 'aaaaaaaaaaaaaaaaaaaaa'
#value: '{{env "GITHUB_SERVER_URL"}/{{env "GITHUB_REPOSITORY"}}/actions/runs/{{env "GITHUB_RUN_ID"}}'
exec:
  default:
    - when: true
      template: default-ok
  hello:
    - when: true
      template: |
        🙅 {{.Vars.buildlink}} 🙅

        exit code: {{.ExitCode}}

        実行されたコマンド

        ```
        $ {{.Command}}
        ```

        Output

        ```
        {{.CombinedOutput}}
        ```

        StdErrOut

        ```
        {{.Stderr}}
        ```
