---
exec:
  default:
    - when: true
      template: default-ok
  hello:
    - when: true
      template: |
        {{template "status" .}} {{template "link" .}}

        exit code: {{.ExitCode}}

        実行されたコマンド

        ```
        $ {{.Command}}
        ```

        Output

        ```
        {{.CombinedOutput}}
        ```

        StdErrOut

        ```
        {{.Stderr}}
        ```
