---
name: Hello

#
# 'on' にしている理由
# yamllintで怒られるため
#
# 参考: https://github.com/adrienverge/yamllint/issues/430
#
'on':
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          submodules: true ## サブモジュールも一緒に checkout (default: false)
      - name: github-commentをインストール
        run: |
          curl -sSfL -o github-comment.tar.gz "https://github.com/suzuki-shunsuke/github-comment/releases/download/v${GITHUB_COMMENT_VERSION}/github-comment_${GITHUB_COMMENT_VERSION}_linux_amd64.tar.gz"
          echo 1da8cb9d52395018ec15f876347e204fe632c833baa1831ca36302dec1e0f97a  github-comment.tar.gz | sha256sum -c
          sudo tar -C /usr/bin -xzf ./github-comment.tar.gz
        env:
          GITHUB_COMMENT_VERSION: 5.0.0
      - name: 古いコメントを削除
        run: |
          #github-comment hide -condition 'Comment.Body contains "test"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: |
          github-comment exec --template .github/github-comment-templates/hello.yaml bash -c 'echo hello'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
